### ISSUE TITLE
Upgrade to Dash 2.0

### ISSUE THREAD

**Issue by xhluca** [plotly/dash-auth#121]
It seems like this imports `dash_html_components`, which is deprecated. So using this library with dash 2.0 creates a warning.

Updating the imports to dash 2.0 style would be nice.

**Comment by alesalloum** [comment]
Yes please!

**Comment by os185059** [comment]
I was going to update it myself, but can I just make a pull request?

Also it looks like builds are failing, so I wanted to make sure all was good.

**Comment by jlondonob** [comment]
Are there updates on this?

**Comment by os185059** [comment]
I have not had time to investigate test failure.

**Comment by lambda-science** [comment]
Any news on this ? Is there any plan for new release that fix this issue ?

**Comment by djmcnay** [comment]
Has there been any update from someone at Plotly?

An additional question is how hard it would be to integrate OAuth2 into dash_auth? Authentication is one of the major stumbling blocks we've found from moving away from R Shiney

**Comment by ned2** [comment]
I set about taking yet another attempt at a PR to update dash-auth to support Dash >=2.0.0 over on this branch: https://github.com/ned2/dash-auth/tree/support-dash2

But I ran into the problem that `itsdangerous` has deprecated support for `JSONWebSignatureSerializer` [in version 2.0](https://itsdangerous.palletsprojects.com/en/2.1.x/changes/#version-2-0-0). Addressing this requires switching to another JWS/JWT library such as `authlib`, or maybe `pyjwt`. Which I don't have a good sense of how to go about doing.

This appears to just be an issue for the Plotly auth components of dash-auth. So for my own needs right now, I've created a branch that strips out the Plotly auth components so that I can get the tests passing for just the basic auth components. https://github.com/ned2/dash-auth/tree/remove-plotly-auth

@alexcjohnson and @chriddyp I'm wondering if the coupling of Plotly Auth and basic auth might now be a bit of a blocker for community PRs bringing the dash-auth up to Dash 2 due to the changes to `itsdangerous`?

**Comment by vflonbeulin** [comment]
+1

**Comment by angusrw** [comment]
+1

**Comment by janeadams** [comment]
+1. There is more background on this in #https://github.com/plotly/dash/issues/1944

**Comment by alexcjohnson** [comment]
Dash Auth v2.0.0 is released to PyPI. This removes `PlotlyAuth` entirely, so Dash Auth only includes `BasicAuth` now. Also dropped Python 2 support, hopefully nobody is still interested in that 😈 

`PlotlyAuth` is only relevant to old versions of Dash Enterprise that literally nobody is using anymore. With that change the package actually doesn't care whether it's run with Dash 1.x or 2.x (though the tests do, they'll now only run on Dash 2.x)

Please test it out and let us know if you run into any issues!
