### ISSUE TITLE
Assets and static files returns 403 with BasicAuth.

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash-auth#57]
Reported by the community:

https://community.plot.ly/t/dash-auth-causes-other-pages-served-by-the-flask-server-to-403/9943

**Comment by ilsl** [comment]
I'm also facing the issue. Will subscribe to this as I can't use dash-auth until this is fixed.

**Comment by pollyannagoncalves-hotmart** [comment]
@T4rk1n any solution for this?

**Comment by javidsch** [comment]
It looks like not only in case of static files/assets.
When opening dynamic URL (it's caught inside callback to refresh page-content), like **http://mydomain/product1/view1**, the response is:

> Access to **"my-domain"** was denied
> You don't have authorization to view this page.
> HTTP ERROR 403

When opening index URI (**http://mydomain/**), it opens basic-auth login page. (ok)

Maybe the issue is related to dash (+components) versions, need to upgrade.

**Comment by olivier-lacroix** [comment]
This has likely been fixed by release 2.1 @alexcjohnson
